### ISSUE TITLE
Enable saving plots

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsbrowse#107]
Bokeh supports saving plots to some degree. We should see if we can use this to export particular views of (e.g.) the mutations browser.

**Comment by benjeffery** [comment]
I've started looking into this, and have a basic png of the mutations plot:
![mutations_scatter](https://github.com/tskit-dev/tsqc/assets/8552/3be6bcc7-01a5-4181-ab76-60fae2a7f169)

This requires `selenium` which is available with a pip install. Are we ok with this as it is a heavy dependency, we could make it an optional one?

**Comment by benjeffery** [comment]
Ah, I realise this issue is focussed on having a save button on the UI when viewing on web. I was mainly thinking about the non-interactive pipeline use case.

**Comment by jeromekelleher** [comment]
Yeah, that's a separate issue

**Comment by benjeffery** [comment]
There's no easy way to screenshot part of a webpage from JavaScript. (You have to play games like re-rendering the html to a canvas) Best way would be to serve pngs made by the API suggested at #158.

**Comment by benjeffery** [comment]
I'm closing this - the bokeh plots already have a save button and doing anything to save larger parts of the page is too complicated.
