### ISSUE TITLE
node plot reset when flags toggled

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#117]
@benjeffery pointed out that toggling the node flags resets the plot,. It would be good to have the zoom unchanged when a node type is checked or unchecked.

**Comment by benjeffery** [comment]
This also happens on the mutations plot when you click log scale. To fix it we need to completely rework how we do the plots, binding the controls and making the plot once rather than making a new plot every time a control changes.

**Comment by jeromekelleher** [comment]
I think the current approach is fine, it's just the way it is.
