### ISSUE TITLE
balance metrics

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#118]
@hyanwong suggested that tree balance metrics might be a good visualisation to include in tsqc, for example, the [Aldous scatterplot](https://academic.oup.com/sysbio/article/55/4/652/1680275). Initially, we could plot histograms for one of the balance metrics implemented in tskit (perhaps in the Trees tab?). This would also give us an idea of compute required for calculating this metric over trees for large datasets.

**Comment by hyanwong** [comment]
Should close this (transferred to https://github.com/tforest/tseda/issues/47)
