### ISSUE TITLE
Disk I/O error on NFS

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#126]
When using the app on a cluster I occasionally get a disk I/O error (screenshot attached), suggesting an issue with the disk caching we're using to store the computed dataframes on NFS.

![image](https://github.com/tskit-dev/tsqc/assets/25925005/1df3920a-fda4-482f-ac29-63afd7da22ec)

**Comment by jeromekelleher** [comment]
My 10c here is that the SQL based approach is adding some unnecessary complexity, with file locks and so on (which NFS doesn't like). A simple file-based approach would be simpler and more debuggable.
