### ISSUE TITLE
Error in Mutations page when zoomed in

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#130]
When we zoom in to the main mutations panel so that no points remain on screen, an error similar to the following is raised in the terminal log:
ValueError: conflicting sizes for dimension 'position': length 375 on the data but length 400 on coordinate 'position'.

Sometimes resetting the plot works (as shown in the video), sometimes it resets to a plot view like the attached screenshot and sometimes the Python process gets killed. I haven't been able to reproduce the last case.

https://github.com/tskit-dev/tsqc/assets/25925005/e4a15e33-c1a8-4b92-963c-b47c8edfb636

![image](https://github.com/tskit-dev/tsqc/assets/25925005/59fdfd67-a411-47b5-b2e9-3801b1d8b672)

**Comment by jeromekelleher** [comment]
Is this reproducible if you disable the linked histograms?

Is there a way to limit the zoom level?

**Comment by savitakartik** [comment]
The ValueError is raised even when the linked tree histograms or axis histograms are disabled. 
I tried setting limits on x and y ranges to restrict the zoom level, but still get the ValueError. Still haven't explored options thoroughly though. Maybe I could use a plot hook to set the axis limits.

**Comment by benjeffery** [comment]
I've tried to recreate this without success - please re-open if you can still trigger it.
