### ISSUE TITLE
Add edge span distribution plot

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsbrowse#132]
It would be helpful to identify when we have lots of very short edges (single site, sometimes). We should add some plot on the edges pane showing the distribution of their spans.

**Comment by jeromekelleher** [comment]
Note that we want to plot this in terms of both the actual edge span as well as the number of sites contained with them

**Comment by savitakartik** [comment]
Could we discuss how best to show these metrics on Monday? Maybe a plot of distribution of edge spans and a plot of edge spans versus number of sites on them?

**Comment by savitakartik** [comment]
Histograms are static, couldn't get them to update smoothly based on area selected in the main Edges plot. Will revisit if I find a way to properly use streams with segments. Some changes remain to be made:
> add a slider to set bin width, so we can see for example, the exact number of 1 bp edges
> add option to calculate spans based on number of sites

**Comment by benjeffery** [comment]
Done in #134
