### ISSUE TITLE
Rename to ``tsbrowse``?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsbrowse#147]
Digesting some feedback, I wonder if we should rename to tsbrowse, as this is primarily an ARG browser (like a genome browser, for ARGs)?

That's definitely better than ``tsviz``, which to my mind would imply visualising the graph.

**Comment by benjeffery** [comment]
Makes sense to me, as it is more than QC at this point.

**Comment by jeromekelleher** [comment]
Tricky though, you don't want to get sucked into adding all the standard genome browser bells and whistles (from a reviewer feedback perspective)

**Comment by petrelharp** [comment]
`tsviewer`?

**Comment by benjeffery** [comment]
tsplot?

**Comment by savitakartik** [comment]
Nice suggestions! Not sure I like it but tsdigest?

**Comment by jeromekelleher** [comment]
tsview?

**Comment by savitakartik** [comment]
tsinspect? (says chatgpt)

**Comment by jeromekelleher** [comment]
I think "browser" is the most accurate description on reflection, and we may as well go with it. We just have to manage expectations regarding feature completeness in terms of variant browsers (which there is no shortage of, and users can always run). 

So, ``tsbrowse``?

**Comment by benjeffery** [comment]
Done in  #166
