### ISSUE TITLE
hide population frequency column

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#151]
In the Mutations page, it would be nice to hide the population-frequency/mutation information by default and only show them on click of a mutation point.

**Comment by benjeffery** [comment]
I've tried for a while to do this and holoviews _really_ doesn't want to mix it's types. Haven't found a way.

**Comment by jeromekelleher** [comment]
We should explore different ways to achieve the same effect, e.g. with a [popup](https://holoviews.org/user_guide/Custom_Interactivity.html#pop-up-panes)

**Comment by benjeffery** [comment]
Fixed by #188
