### ISSUE TITLE
Blank Nodes/Edges panels

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#178]
When the Edges and Nodes pages load, the main (datashaded) plots are all blank initially. The plots appear on first user interaction (plot refresh/pan/zoom), but ideally we should not have blank plots initially.

https://github.com/user-attachments/assets/54fa8246-6466-401c-bcbc-f9a2db83c9e2

**Comment by benjeffery** [comment]
I believe this is fixed by #177
