### ISSUE TITLE
Blank mutations plot caused by all mutations being "unknown"

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsbrowse#185]
We should alert the user somehow when mutation times are unknown. This has caused some of the confusion over at #179, where old `.trees` files from the unified genealogy have no mutation time.

**Comment by benjeffery** [comment]
I note at https://github.com/tskit-dev/tsbrowse/blame/1f3bfbd77b9a66725d9399a64fa64059e5f002d7/tsbrowse/model.py#L418 @jeromekelleher suggests using the compute mutation times routine from tskit.

**Comment by jeromekelleher** [comment]
Emitting a warning and computing times seems the right approach
