### ISSUE TITLE
redundant columns in table viewer

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#189]
We should review the columns displayed in the Table viewer page, as some are redundant. For example, `parent_time` and `parent_time_right` refer to the same column. This is required because Holoviews needs separate y0 and y1 columns to display an edge as a segment, but we don't need to display these in the viewer.

**Comment by jeromekelleher** [comment]
I think we can resolve this at the same the same time as #191 by explicitly specifying the columns to display and their order somewhere
