### ISSUE TITLE
edges table viewer: incorrect right coordinate displayed?

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#190]
![Screenshot 2024-10-11 095758](https://github.com/user-attachments/assets/8a1f29b3-6df9-478c-ad09-6454469facea)

![image](https://github.com/user-attachments/assets/10ac69ed-4701-4825-b4ae-8fb5353da377)

There seems to be a difference between the right coordinates displayed in the Edge table viewer vs the tree sequence edges table.

**Comment by savitakartik** [comment]
I'm not sure the correct coordinates are displayed in Edges plot either, so it could be that somehow the wrong coordinate is recorded in the edges_df. I'll dig into it!

**Comment by benjeffery** [comment]
I've not been able to replicate this in a couple of tree sequences I tried.

**Comment by savitakartik** [comment]
We've discused this already, but posting here so I don't forget: we think it's likely because in the edges_df we end up representing edges in terms of site IDs, instead of genomic coordinates.

**Comment by benjeffery** [comment]
Of course! We aren't dequantising the tszip columns! I'll add some more tests here - I should have caught this in the preprocessing tests.
