### ISSUE TITLE
column order in table viewer

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#191]
Should we ensure that columns are always displayed in the same order in the Table viewer? 

![image](https://github.com/user-attachments/assets/6c1a83ec-e7f7-410b-8ca5-f6b668585796)
![image](https://github.com/user-attachments/assets/37d7ae7b-84b5-44b1-92a4-76275193d40e)

**Comment by jeromekelleher** [comment]
We also want to group the columns logically - maybe starting with the "real" columns, and having the additional ones at the end?
