### ISSUE TITLE
Mutations plot fails on sc2ts Wide ARG

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsbrowse#197]
We get an empty plot when clicking on mutations tab
![Screenshot from 2024-10-14 11-00-00](https://github.com/user-attachments/assets/15a9b17b-12ea-4a0f-99cd-93714a6b47d1)

**Comment by benjeffery** [comment]
Works on my machine! What browser are you on?
![Screenshot at 2024-10-14 17-07-35](https://github.com/user-attachments/assets/d6dd3e74-7b5f-4eec-a600-90df84936e53)

**Comment by benjeffery** [comment]
Fixed with updating deps
