### ISSUE TITLE
defining a viewport with controls

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#198]
Sometimes, we might want to manually define a viewport on the main Mutations/Nodes/Edges plots. For example, when comparing plots across datasets, or examining a specific genome-time slice, this might help to more easily define x and y limits rather than use the Bokeh pan/zoom controls. We could do this with x- and y-axis textboxes or slider widgets on the sidebar.

**Comment by benjeffery** [comment]
I assume we want this to be a multi-directional binding, as in any drag change to any plot is reflected in all other plots and the numeric control?

**Comment by jeromekelleher** [comment]
Just a simple per page control that has no global state would be better I think.
