### ISSUE TITLE
Tree sequence filename is truncated to 15 characters

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#200]
With the new page layout, the filename of the tree sequence is shortened to 15 characters to fit next to the tabs. The tree sequences I work with usually have long filenames where the important bit as at the end, so this is quite limiting:

![image](https://github.com/user-attachments/assets/ffec14be-4596-40bc-8d46-c0e583e3e4c0)

The simplest solution would be to have the full filename shown when mousing over the title. The tab title also doesn't need to be shortened. We could perhaps display the full filename at the top of the Overview tab, along with the provenance details?

**Comment by benjeffery** [comment]
Fixed by #201
