### ISSUE TITLE
Documentation site/page

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsbrowse#209]
`tsbrowse` needs a page with:

- brief into
- installation
- getting started
- example tree sequence files
- quick summary of each page.

This seems too lightweight to need a full sphinx build. I suggest we have a markdown file with a few screenshots that gets compiled to HTML by a simple script and then pushed to tskit.dev by the site CD action.

**Comment by savitakartik** [comment]
I can write these sections. I'm guessing we could resuse some of the material from the paper which I'm already working on anyway.

**Comment by benjeffery** [comment]
Ok I'll get infrastructure set up.
