### ISSUE TITLE
Add convenience function that preprocesses a TS then serves the app

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#211]
The preprocessing approach is working a lot better than previous versions in the GEL research environment with terrible performance. My only concern with the new workflow is that I always want to serve the app when I preprocess a TS, so having to run the `preprocess` command, then copy the `serve` command and paste it into the shell is a bit inconvenient. This is particularly true with the awful shell performance in GEL, where each step takes a while to complete. I would find it very helpful to have an additional command that combines them, if that doesn't go against the new paradigm too much?

**Comment by jeromekelleher** [comment]
Don't see any reason not to. Suggestions for names and semantics?

**Comment by benjeffery** [comment]
How about a `--preprocess` option to `serve`?

**Comment by jeromekelleher** [comment]
Which writes the .tsbrowse file by appending the suffix to the input path? SGTM

**Comment by benjeffery** [comment]
Yeah, that's the default behaviour of `preprocess`, we'd match that.

**Comment by duncanMR** [comment]
That sounds great to me: thanks!
