### ISSUE TITLE
Plot the distribution of mutations in time and genomic space

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#23]
Since every mutation in a tree sequence is associated with a node, I think it might be helpful to visualise mutations in a ts using associated node times and flags in addition to the site location. That way, we can see if there are abnormally high numbers of mutations being thrown onto lower parts of the tree and we can also spot genomic regions with low coverage. I hacked together some code to do this:

```python
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import tsinfer
import tskit

def describe_flag(flag):
    ### Determine a node's type based on its flag
    if flag & tskit.NODE_IS_SAMPLE:
        return "Sample"
    if flag & tsinfer.NODE_IS_PC_ANCESTOR:
        return "Path-compressed ancestor"
    if flag == 0:
        return "Inferred ancestor"
    else:
        raise ValueError("Unknown flag")
flag_names = ["Inferred ancestor", "Sample", "Path-compressed ancestor"]

def plot_mutations_spectrum(
    ts,
    flag_colors=["#1f77b4", "#d62728", "#ff7f0e"],
    log_time=True,
    log_time_offset=0.01,
    plot_path=None,
    fig_size=(15, 8),
    num_bins=8,
    point_size=5,
    alpha=1,
):
    ### Plot the mutations in a tree sequence by genomic position and associated node time.
    ### Include a histogram of mutation frequency.

    # Create mutation dataframe
    sites = ts.tables.sites
    data = []
    for tree in ts.trees():
        for mutation in tree.mutations():
            node = mutation.node
            mutation_time = tree.time(node)
            mutation_log_time = np.log10(
                mutation_time + log_time_offset
            )  # Add constant to avoid log(0)
            flag = ts.nodes_flags[node]
            node_type = describe_flag(flag)
            position = sites[mutation.site].position * 1e-6  # Convert to Mb
            data.append(
                {
                    "time": mutation_time,
                    "log_time": mutation_log_time,
                    "flag": flag,
                    "node_type": node_type,
                    "position": position,
                }
            )
    df = pd.DataFrame(data)

    # Plot the dataframe
    time_column = "log_time" if log_time else "time"
    plt.figure(figsize=fig_size)
    grid = gridspec.GridSpec(1, 2, width_ratios=[3, 1])

    # Determine time units
    if ts.time_units == "uncalibrated":
        time_units = "Frequency"
    else:
        time_units = ts.time_units

    # Create scatter plot on first subplot
    color_dict = dict(zip(flag_names, flag_colors))
    scatter_ax = plt.subplot(grid[0])
    for node_type, color in color_dict.items():
        subset_df = df[df["node_type"] == node_type]
        subset_df.plot.scatter(
            x="position",
            y=time_column,
            color=color,
            ax=scatter_ax,
            label=node_type,
            s=point_size,
            alpha=alpha,
        )
    scatter_ax.set_xlabel("Position (Mb)")
    scatter_ax.set_ylabel(f"Log({time_units})" if log_time else time_units)
    scatter_ax.set_title("Distribution of mutations across the genome")
    scatter_ax.legend(loc="upper left")

    # Create histogram on second subplot
    hist_ax = plt.subplot(grid[1], sharey=scatter_ax)
    df[time_column].plot.hist(
        orientation="horizontal",
        color=flag_colors[0],
        ax=hist_ax,
        edgecolor="black",
        linewidth=1,
        bins=num_bins,
    )
    hist_ax.set_xscale("log")
    hist_ax.set_xlabel("Count")
    hist_ax.set_title(f"{time_units} histogram")

    # Adjust space between plots and save
    plt.subplots_adjust(wspace=0.05)
    if plot_path:
        plt.savefig(plot_path, dpi=300, bbox_inches="tight")
    plt.show()
```
Here is an example of what the plot looks like:
<img width="1025" alt="mutation_spectrum_simulation" src="https://github.com/tskit-dev/tsinfer-qc/assets/5416474/5e407708-466e-493a-b2e9-ba4b08cdd066">
The histogram on the right should correspond to the allele frequency spectrum, since this is an undated ts. I made the example by simulating an expanding population with stdpopsim, then running tsinfer on the resulting sample data:
```python
import stdpopsim

species = stdpopsim.get_species("HomSap")
model = species.get_demographic_model("OutOfAfrica_3G09")
contig = species.get_contig("chr22", length_multiplier=0.1)
samples = {"YRI": 0, "CHB": 0, "CEU": 1000}
engine = stdpopsim.get_engine("msprime")
ts_sim = engine.simulate(model, contig, samples)
sd = tsinfer.SampleData.from_tree_sequence(ts_sim)
anc = tsinfer.generate_ancestors(sd)
anc_ts = tsinfer.match_ancestors(sd, anc)
ts = tsinfer.match_samples(sd, anc_ts)
plot_mutation_spectrum(ts, log_time=True, point_size=5, alpha=1)
```
I also applied it to some trees inferred from a 5K subset of the Genomics England data on chromosome 22. It's interesting to see how many more path-compressed node mutations there are compared with the simulated data, and also the regions where there are little to no mutations:
<img width="1025" alt="mutation_spectrum_gel" src="https://github.com/tskit-dev/tsinfer-qc/assets/5416474/7ccce63e-e5b0-4799-979f-88fe2e0bbfdf">

**Comment by jeromekelleher** [comment]
This is nice. It would be good to compute the mutation times more efficiently (we want these plots to be quick) - this feels like something we should be doing in tskit. Is there a way to do it at the moment?

**Comment by duncanMR** [comment]
What is inefficient about the tree.time method? Is it copying the whole node table each time?

**Comment by jeromekelleher** [comment]
These loops will be expensive:
```python
  for tree in ts.trees():
        for mutation in tree.mutations():
            node = mutation.node
```
Really what we want is just the ``ts.mutations_time`` array, filled out with either the time of the mutation's node (if it's not null). Something like this:
```python
mutations_time = ts.mutations_time
unknown = mutations_time == tskit.MUTATION_TIME_UNKNOWN # or whatever it is
mutations_time[unknown] = ts.nodes_time[ts.mutations_node[unknown]]
```

This should really be a method in tskit though - maybe you could follow up with this by opening an issue linking here, so we can discuss the API?

We should be aiming to use the numpy approach in this plotting code for as much as possible to keep it quick.

**Comment by duncanMR** [comment]
[It turns out there is a mutation time method built into tskit!](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TableCollection.compute_mutation_times) Sorry I missed it! It computes the time as the mean of the parent and child node times, so the result looks different, but I think it makes sense. Here is the updated code to compute the dataframe:

```python
    vectorized_describe_flag = np.vectorize(describe_flag)
 # Create mutation dataframe
    tables = ts.dump_tables()
    tables.sort()
    tables.build_index()
    tables.compute_mutation_times()
    mutations = tables.mutations
    mutation_time = mutations.time
    mutation_log_time = np.log10(time + log_time_offset)
    ts = tables.tree_sequence()
    flag = ts.nodes_flags[mutations.node]
    node_type = vectorized_describe_flag(flag)
    position = ts.sites_position[mutations.site]
    array = np.column_stack([position, mutation_time ,mutation_log_time, node_type])
    df = pd.DataFrame(array, columns=["position", "time", "log_time", "node_type"])
    df = df.astype({"position": "float64", "time": "float64", "log_time": "float64"})
```

This is what the plot looks like for the simulated data:

![mutation_spectrum](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/d4db3e91-937a-439d-98fe-3c7a86c58c74)

As you can see, the sample node mutations are spread out in time because they get pulled up the time of the parent node. The `timeit` tests I did show that the new method is about 6 times faster for this data. @jeromekelleher do you think this is efficient enough?

**Comment by jeromekelleher** [comment]
Hmm, not sure we do want to use ``compute_mutation_times`` here, the mean will be misleading for this analysis.

Anything using the vectorised operations is ~ as fast as it's going to get.

**Comment by duncanMR** [comment]
I agree: it isn't ideal how the sample node mutations are pulled upwards. I just posted the tskit issue above.
