### ISSUE TITLE
Edges and nodes plots shrink to nothing upon interaction

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#234]
Using the [latest GitHub build](https://github.com/tskit-dev/tsbrowse/commit/a08d2a1a62ae79779483f13e5cb087e491d9e2d8) I'm getting a strange bug with a simple inferred tree sequence I'm working with. As soon I interact with the nodes or edges plot, the axes of the plot shrink to nothing. Changing any of the plot settings on the left or switching tabs back and forth resets it:

![image](https://github.com/user-attachments/assets/c225f1d8-c60b-4f16-8a9a-d4da84817065)

Oddly, there is no such problem with the mutations tab. I tested it in Chrome and Firefox with the same results. Here are the TS and TSBROWSE files I'm working with:

[smc_test.zip](https://github.com/user-attachments/files/17813109/smc_test.zip)

I generate the TS using the following code:

```python
import msprime
import tsinfer

ts_base = msprime.sim_ancestry(
    50,
    sequence_length=1e6,
    random_seed=2,
    recombination_rate=1e-8,
    population_size=1e4,
    model="smc_prime",
)
sim_ts = msprime.sim_mutations(ts_base, rate=1e-8, random_seed=2)
sample_data = tsinfer.SampleData.from_tree_sequence(ts)
test_ts = tsinfer.infer(sample_data, num_threads=8)
test_ts.dump('data/trees/smc_test.trees')
```

**Comment by benjeffery** [comment]
Yep, I've seen this. I think the responsive elements are somehow thinking they have zero size.

**Comment by jeromekelleher** [comment]
Ditch responsive?
