### ISSUE TITLE
Case study: ancestor trees of a subset of Genomics England data

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#32]
I thought it might be helpful to showcase various plots from this project in an example. As I discussed in the last tskit meeting, we are seeing highly fragmented ancestors in the trees inferred from GEL data (5000 samples on the q-arm of chr22), with more mutations than you'd expect. Since then, I've applied some of @savitakartik's plots to the ancestor trees, which has been quite revealing:

![image](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/55dfcbd7-e482-4e82-988b-9bb3b936273d)

We have heavy tails in the distributions of both mutations-per-node and mutations-per-site. We can also see this in the `mutations_per_site_along_seq` plot, showing three sites with over 1000 mutations! 

![image](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/b415fc96-433c-4797-a65c-85402e01a24a)

Now let's look more closely at the nodes with the highest mutation counts. The top twenty nodes all have over 300 mutations. There are 6352 mutations on these nodes, yet they are spread over only 848 unique sites. 

![image](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/9ea016f9-a9e9-46e1-a585-a100ef6eda5d)

What do these nodes look like? Below is the ancestors plot (#25) of the node with the most mutations. I've modified the code to include faint lines for each ancestor the node copies from. That way, we can see whether we are copying little fragments from larger ancestors or using the whole length. 

![image](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/8591fc3c-d5eb-4d67-9423-da5e1f04f2dc)

We can see that we've generated a bunch of short ancestors (shown in red on the right) which have been path-compressed into nodes in the recent past (shown in orange on the left) below which there are hundreds of mutations. You can ignore the 1.5 mbp region on the left, since this corresponds to the p-arm and centromeric region which we don't have trees for. The second most problematic node is a simpler case:

![image](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/c2131a0a-730f-4016-b074-cdba7f259e4a)

Just one parent PC node, which in turn compresses 33 ancestors that share a timepoint. Remarkably, the PC node is parent to 16 other nodes, each with at least 60 mutations!

![image](https://github.com/tskit-dev/tsinfer-qc/assets/5416474/bb231ce9-cc07-47f7-86b0-6d13b637a921)

The high numbers of mutations might be explained by the fact that we didn't use a mismatch ratio of zero when matching ancestors here. However, the problem remains that we seem to be generating highly implausible ancestors. We still have to figure out exactly what is causing the problem with ancestor generation.

**Comment by jeromekelleher** [comment]
Great work, thanks @duncanMR :muscle: Food for thought...
