### ISSUE TITLE
Add populations to overview

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#74]
It would be good to have a separate tabs for (a) populations and (b) provenances which can both be obtained form the tree sequence metadata. We could list all populations represented in the tree sequence in a table, and also show the number of nodes within each. For the provenance tab, it would just be a list of the provenance fields. Alternatively, we could display this information int he Overview page.

**Comment by jeromekelleher** [comment]
A minor point - the tree sequence metadata is technically separate from the provenance and population tables, which are "first class" members of the data model. Metadata is technically anything that is stored in a ``metadata`` field, and external to the tskit data model.

**Comment by savitakartik** [comment]
I see, thanks for the clarification.

**Comment by benjeffery** [comment]
Closing this as provenance information is now displayed on overview and population info is now viewable from the tables viewer.
