### ISSUE TITLE
Overview page

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsbrowse#76]
We're currently displaying a tree sequence summary on the landing page. In addition, we might want to display the summary that we're already creating for a TSModel object. We could also add a tabulator widget to show additional summary stats that we aren't reporting in other pages. Another useful addition may be the provenance entries and populations corresponding to the tree sequence (although we might decide to display these in separate pages; see issue #74 ).

**Comment by hyanwong** [comment]
Provenance is good. It would be nice to know if this TS is supposed to come from a particular species (and if, e.g. humans, which genome build it corresponds to, etc: it would be nice if this played well with the stdpopsim metadata fields / reference genome)

**Comment by benjeffery** [comment]
Provenance will be present if tskit >= 0.5.9 is used. Please open issues if there are other specific things to add to overview.
