### ISSUE TITLE
Extra plots on the "overview" panel?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsbrowse#95]
Are there any plots we might want as an "overview" of the whole TS? E.g. I wonder if it would be helpful to have the AFS (both branch-wise and, if there are mutations, the site-wise version overlaid) on the overview panel, next to the table information? I guess it depends how quick it is to generate this for the entire TS?

**Comment by jeromekelleher** [comment]
I think we want to keep the overview pretty minimal, otherwise it becomes hard to know which plot goes on the overview and which goes on the sub-tabs.

**Comment by benjeffery** [comment]
Closing for now - if there are concrete ideas for extras on the overview page please raise them as separate issues.
