### ISSUE TITLE
Add option to window the popgen plots over n trees

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#97]
Gertjan Bisschop suggested that we add another option for windowing the Popgen tab plots, such that each window covers n trees for a given n. At the moment, we can either choose a fixed number of windows or have one window per tree (i.e. n =1).

**Comment by benjeffery** [comment]
Tsqc is just exposing the tskit options here, I don't think multiple trees is an option. Could be though if someone wanted to implement it.

**Comment by jeromekelleher** [comment]
Would be easy enough, something like
```
windows = ts.breakpoints(as_array=True)[::k]
```
would pull out every kth breakpoint (but would need some special handing of the trailing values) I think?

**Comment by benjeffery** [comment]
Popgen tab has been shelved so closing for now.
