### ISSUE TITLE
View random subset tree for a particular location?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsbrowse#99]
Sometimes you do just want to look at the trees. 

Could we add a panel where we show the SVG tree at a give location for some (random) subset of the samples, where the size of the subset is an option?

This is a can of worms, but maybe we could do something simple and it would be good enough?

**Comment by hyanwong** [comment]
I think this is likely to be part of tseda, e.g. https://github.com/hannamlmv/tseda/pull/104#issuecomment-2527582594

We should add an option in there to subset the samples, maybe. I'll open an issue on that repo.
